### ISSUE TITLE
When an engineer is doing X-fer me with both an adjectant engineer and base, X-fer is being done between the engineers even if has 0 rescources

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MAXTouch-docs#11]
Instead of x-fer material between base & engineer
Suggestion : give priority to xfer between base instead of adjectant units like engineer, constructor ..

**Comment by KatekovAnton** [comment]
can you explain step by step? repharase

**Comment by Malakia1** [comment]
![Screenshot_2019-12-21-19-14-44-831_org oldgamesalive games maxandroid](https://user-images.githubusercontent.com/58878574/71311996-4e587a80-2426-11ea-885b-5ff44efa8990.jpg)
Xfer me, result 0 xferred, tries to xfer from other empty engineer

**Comment by Malakia1** [comment]
![Screenshot_2019-12-21-19-14-59-879_org oldgamesalive games maxandroid](https://user-images.githubusercontent.com/58878574/71312012-81027300-2426-11ea-8311-fd5379d30d01.jpg)
Xfer, result, 0 xferred, tries to xfer from missile launcher

**Comment by Malakia1** [comment]
![Screenshot_2019-12-21-19-15-07-867_org oldgamesalive games maxandroid](https://user-images.githubusercontent.com/58878574/71312032-b73ff280-2426-11ea-9036-2c8e6c4ea9b2.jpg)
Xfer, result, 40 xferred from base, as should be

**Comment by KatekovAnton** [comment]
@Malakia1 Is it a bug? I think it just choses the wrong unit to take resources...

**Comment by Malakia1** [comment]
If there is an adjectant base and a unit to choose from, xfer me always chooses the unit.
But in 99% of the time you would want to xfer materials from the base, not another unit.

**Comment by KatekovAnton** [comment]
I think it should be fixed already... please reopen if not
