### ISSUE TITLE
[Android] Zoom in and out stops working

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MAXTouch-docs#12]
In Android only zooming sometimes stops working
If you leave MAX touch open after doing your turn, sometimes when you start another turn zooming stopped working 

v12.0.0 beta 3

**Comment by KatekovAnton** [comment]
@Malakia1 provide step-by-step instruction please

**Comment by Malakia1** [comment]
There's no specific instructions i can give
Eventual zooming will stop working. 
It allways occurs when you start your turn or watch turn replay.. Never in the middle of a turn..
Only when max touch was left open before.. 
Found no specific time frame or event that triggers it

**Comment by KatekovAnton** [comment]
@Malakia1 did some changes, please check... #12.0.1.b1
