### ISSUE TITLE
[Android] Game crashes right after turn replay

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MAXTouch-docs#13]
Much reoccurring bug. +- 1 in 10 games
After replay is finished, Max touch crashes in the first few seconds you start your turn.
Same when skipping replay.
In my observation this bug only starts happening in the early turns (+- 3 - 10 turns) 
You have to play on another OS to be able to continue the game
After a few turns the bug disappears. 
In my experience this bug has never occured in the later stages of the game...

**Comment by KatekovAnton** [comment]
@Malakia1 check in #12.0.1.b1
