### ISSUE TITLE
When you try to load a unit on another cell with an air transport, but there is allready a unit on the cell of the air transport, the air transport selects that unit to load 

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MAXTouch-docs#15]
v12
![2019-12-21_20h05_34](https://user-images.githubusercontent.com/58878574/71312674-d1c99a00-242d-11ea-9e6c-5eae7bf14a65.png)
can not select RL left of AT to pick up, selects RL on same cell instead

**Comment by KatekovAnton** [comment]
Fixed in v12 b7
