### ISSUE TITLE
Unit lock : it's better to able to select / deselect units then showing scan/attack range of every unit that has been clicked

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MAXTouch-docs#16]
![Screenshot_2019-12-21-20-33-30-743_org oldgamesalive games maxandroid](https://user-images.githubusercontent.com/58878574/71312925-a6e14500-2431-11ea-9cdf-27c8f63fff3c.jpg)
In touch, when unit LOCK is enabled, it will show scan & attack range of every unit that has been clicked.
Imo,it's much more useful to be able to select and deselect specific units, like in original M.A.X.

**Comment by KatekovAnton** [comment]
Will not be fixed
