### ISSUE TITLE
Where a bridge is built on shore cells, sea units can enter this cell (which they normally can't) 

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MAXTouch-docs#17]
![2019-12-21_23h29_11](https://user-images.githubusercontent.com/58878574/71314565-c9338c80-244a-11ea-89bf-d81a20385d9c.png)
![2019-12-21_23h30_49](https://user-images.githubusercontent.com/58878574/71314566-ca64b980-244a-11ea-9cbe-06b84464fd41.png)
In this example an enemy unit sailes through 2 shore cells, where no sea units can go (i checked, destroyed the bridges and verified those can't be accessed by sea units)
The enemy sub also was detected when under the bridges, to become invisible again when entering a normal sea cell.
v11.0.3

**Comment by KatekovAnton** [comment]
Fixed in v12 b7
