### ISSUE TITLE
[Android] if you swipe in additional menu max touch crashes

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MAXTouch-docs#18]
V12.0.0 beta 6
![Screenshot_2019-12-22-11-25-17-645_org oldgamesalive games maxandroid](https://user-images.githubusercontent.com/58878574/71320726-d8005a80-24af-11ea-8283-704b3c880f85.jpg)

**Comment by KatekovAnton** [comment]
Fixed in v12 b7
