### ISSUE TITLE
(Enemy) Subs are being detected when moving under bridges (v12 b8)

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MAXTouch-docs#20]
was mentioned in https://github.com/KatekovAnton/MAXTouch-docs/issues/17 
Sea units entering shore tiles was fixed in v12 b7 
Subs however are still being detected when entering a cell with bridges, to be undetected again when entering an empty sea cell. 

expected behaviour: submarines stay undetected when moving under bridges

v12 b8

**Comment by KatekovAnton** [comment]
Expected behavior.
