### ISSUE TITLE
Low ammo sound alert issue

### ISSUE THREAD

**Issue by marcu805** [KatekovAnton/MAXTouch-docs#21]
Not a bug, but more an alert issue 

Don't know if it was discussed before.

Observed behaviour:
For example, when fighter remains 1/4 ammo and is also damaged, the "ammo is low" sound do not appear and don't alert that you are almost out of ammo, instead the alert sound which appear is the one about the status. 

Expected behaviour:
Even if the unit is damaged, but out of ammo (or low ammunition), the alert sound should be related to ammo, not status, because is more important the ammo aspect, as the damage is seen in the bar under the unit.

An alert icon, as you discussed on Discord channel, would help. But I think also the sound alert matters.

**Comment by KatekovAnton** [comment]
done in 15.0.0b9
