### ISSUE TITLE
[Suggestion] Stats window suggestion

### ISSUE THREAD

**Issue by marcu805** [KatekovAnton/MAXTouch-docs#22]
I think if stats are shown also in red (when they are almost depleted) as in previous HUD, it would make them more intuitive. As observed, red color is maybe not the best option for window's background. But seems decent enough.

Or better... only for ammo and gas. Because otherwise draws off the attention too much.

![screen1](https://user-images.githubusercontent.com/59109129/71449438-4d408980-2755-11ea-9495-fdfafd5a1101.jpg)

![screen2](https://user-images.githubusercontent.com/59109129/71449442-516ca700-2755-11ea-9511-fefe6d89a8e3.jpg)

![screen3](https://user-images.githubusercontent.com/59109129/71449443-5598c480-2755-11ea-9a03-600051db21fe.jpg)

**Comment by KatekovAnton** [comment]
we can swithch to orange

**Comment by KatekovAnton** [comment]
![Untitled](https://user-images.githubusercontent.com/992894/99973669-5ada1580-2de3-11eb-8f77-73811590eace.png)

**Comment by KatekovAnton** [comment]
fixed in v15.0.0b8
