### ISSUE TITLE
Air transport unloads units to adjectant cells instead of same cell

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MAXTouch-docs#23]
![2019-12-27_21h33_25](https://user-images.githubusercontent.com/58878574/71548463-a6572a00-29ae-11ea-93b0-d4ed6c1d45a1.png)
![2019-12-27_21h35_15](https://user-images.githubusercontent.com/58878574/71548464-a6572a00-29ae-11ea-86ad-18b411784a8d.png)

What i did : 
Moving air transport to position in screenshot
Unload unit, instead of unloading on the same cell as air transport, it gives the option to unload on adjectant cells

Appearance :
Could not reproduce, moving the air transport to another cell : unloads on the same cell
moving back to the original spot : unloads on the same cell

Info:
Windows v12 b8

Observation : 
Air transport seems to be in landed position, is under connector in screenshots, although there is no landing pad.

Same bug has been posted by one other player on Discord, there was no connector on that cell in his example

**Comment by KatekovAnton** [comment]
cannot reproduce
