### ISSUE TITLE
If there is a unit on the same cell of an air transport it's impossible to select a unit on another cell for loading, it will select the unit on the same cell for loading

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MAXTouch-docs#25]
Steps to reproduce :
select load with your air transport, to load a land unit on another cell
a land unit is present on the same spot of the air transport 
the air transport automatically selects the unit on the same cell
you can't select the unit on another cell unless first moving to another cell without a land unit

Expected behaviour: 
you should still be able to select the other unit for loading
if you click on the other unit when loading was enabled on the air transport, the other unit should be selected for loading, when clicking again on the other unit, the air transport should move to that cell and load that unit. 

Can be reproduced
v12

**Comment by KatekovAnton** [comment]
Fixed

**Comment by KatekovAnton** [comment]
Fixed in #12.0.1.b1
