### ISSUE TITLE
[v11.0.3]: Newly created MobileAA unit disabled for 5 turns after deployment from factory

### ISSUE THREAD

**Issue by Slobjok** [KatekovAnton/MAXTouch-docs#27]
In a v11 game played in v11.0.3 (but in the past was also played with V12 betas):
I've created a new Mobile AA unit in a light factory and then during my turn moved it out of the factory. As soon as clicking on the deployment-square besides the factory, the unit was displayed as disabled for 5 turns.

**Comment by KatekovAnton** [comment]
@Slobjok can you give steps to reproduce? or game name?
