### ISSUE TITLE
[Suggestion] Show damage from splash

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MAXTouch-docs#29]
When a unit with splash attack selects a unit for attack, it would be great if the damage that will be done by the splash damage on units/buildings in surrounding cells is also shown
 (as it is shown for the unit that is selected for attack)

**Comment by 1GodRage** [comment]
You use Rockets too much 😄

**Comment by Hruks** [comment]
<img width="400" alt="Screenshot 2021-02-07 at 14 48 42" src="https://user-images.githubusercontent.com/556824/107146106-1b898280-6957-11eb-998e-abeac397ccd8.png">
<img width="477" alt="Screenshot 2021-02-07 at 14 48 24" src="https://user-images.githubusercontent.com/556824/107146111-204e3680-6957-11eb-823e-6884a2b5aee8.png">

**Comment by KatekovAnton** [comment]
#15.1.2
