### ISSUE TITLE
[Android] On a Galaxy Tab A 2019, alignment is off, tapping on a unit or menu actually selects/clicks a position about a cm lower

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MAXTouch-docs#30]
On a Galaxy Tab A 2019, alignment is off, tapping on a menu actually clicks a position about a cm lower.
Encountered on Android 9, on a Galaxy tab A 2019  (sm-t510). (mine as well as another's players tablet).
Resolution 1920 x 1200 pixels (WUXGA).
Ingame about a cm of the top of the screen is left black, the width corresponds with the distance you click lower then where you've actually tapped (see image).
v12.0.0

![Screenshot_20200112-211000_MAXAndroid](https://user-images.githubusercontent.com/58878574/72286129-ce988700-3644-11ea-80b7-f9ca0643d0d3.jpg)

**Comment by KatekovAnton** [comment]
Should be fixed in #12.0.1.b1
