### ISSUE TITLE
[Suggestion] Ability to change the order in which the players do their turn

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MAXTouch-docs#31]
Especially useful for team games, because you want the players to be in a logic order : t1/t2/t1/t2 or t1/t1/t2/t2
Currently a lot of times, one or more players needs to leave and re-enter the game to get the right order.
An up and down button would be nice, simular like how we now set teams

**Comment by KatekovAnton** [comment]
UI is done but need some fixed on server side.

**Comment by KatekovAnton** [comment]
done in 15.0.0b8
