### ISSUE TITLE
[Android] Zoom in and out stops working

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MAXTouch-docs#32]
In Android only zooming sometimes stops working
If you leave MAX touch open after doing your turn, sometimes when you start another turn zooming stopped working

Duplicate of closed issue https://github.com/KatekovAnton/MAXTouch-docs/issues/12
because issue still occurs in v12.0.1 beta2

**Comment by KatekovAnton** [comment]
should be fixed in #v13.0

**Comment by Malakia1** [comment]
Still issue still persists (v15 + v16 beta)
