### ISSUE TITLE
v13 - everything is in BOLD in dock / hangar etc instead of only the things that can be updated...

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MAXTouch-docs#35]
In v13.0:
![2020-04-28_09h18_03](https://user-images.githubusercontent.com/58878574/80511623-a24b1100-897c-11ea-9999-591a3a3b6962.png)
 everything that can be updated (refuel/repair/upgrade...) is in bold even if there is nothing to be updated (eg. unit is not damaged)

Expected behaviour : only the things that can be updated are displayed in bold

**Comment by Malakia1** [comment]
Expected behaviour screenshot
![2020-04-28_09h30_50](https://user-images.githubusercontent.com/58878574/80511685-b7c03b00-897c-11ea-91e5-0d9c03d6f4b1.png)

**Comment by KatekovAnton** [comment]
fixed in 15.0.0b9
