### ISSUE TITLE
[Bug] Gold on the UI and Gold to invest are differents

### ISSUE THREAD

**Issue by 1GodRage** [KatekovAnton/MAXTouch-docs#37]
I found a bug, the gold bug, the gold not being well displayed on the "main window" , letting me think that the gold didn't income during this turn. But, when I open the gold refinery there is gold income !!!
This bug is here since years. It may have even cost me a game or 2. :P
Anyway, here I catched it. But I don't know how to reproduce it.
**Windows v13.0.2**
![goldbug](https://user-images.githubusercontent.com/63362446/81346512-b0a2d680-90ba-11ea-83c7-e80e04eac1ea.png)

**Comment by KatekovAnton** [comment]
done in 15.0.0b9
