### ISSUE TITLE
[Suggestion] Energy needed icon.

### ISSUE THREAD

**Issue by 1GodRage** [KatekovAnton/MAXTouch-docs#38]
Energy producers have 3 times the same energy icon.

We need a different energy icon for the "needed energy for the basement".

Here is a simple fix I proposed years ago:
![energy-understanding](https://user-images.githubusercontent.com/63362446/81346742-1a22e500-90bb-11ea-929c-e6a361709077.png)

After few hundreds turns, it can be difficult to remember which one is the produced one, and which one is the "needed" one.

---
Better understanding of Energy :
acutally both are the "energy" logo.
Change the "needed energy of the complex" by the "connector" logo.
So, only energy produced will have the "energy" logo.

_(**GodRage** on 21/11/2018)_

**Comment by Hruks** [comment]
What do you think about next icons?
<img width="206" alt="Screenshot 2021-01-16 at 18 09 28" src="https://user-images.githubusercontent.com/556824/104815559-53a11800-5826-11eb-89d7-18578dd8e42e.png">
<img width="173" alt="Screenshot 2021-01-16 at 18 09 12" src="https://user-images.githubusercontent.com/556824/104815561-56037200-5826-11eb-9b08-d5c093bea067.png">

**Comment by Hruks** [comment]
Implemented and Released in version 15.1.0 beta 7
