### ISSUE TITLE
When 'auto xfer on laying' is enabled engineer takes materials from adjectant trash tiles

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MAXTouch-docs#4]
When 'auto xfer on laying' is enabled an engineer laying roads or connectors takes materials from adjectant trash tiles.
When you finish turn the material in the trash tiles is reset, so you get the material for free
V12.0.0 beta 3

**Comment by Malakia1** [comment]
![2019-11-28_21h55_47](https://user-images.githubusercontent.com/58878574/70985791-ff74b300-20bc-11ea-899d-a42fd376c7bc.png)
![2019-11-28_21h57_11](https://user-images.githubusercontent.com/58878574/70985793-ff74b300-20bc-11ea-9282-de127f51ff2f.png)

**Comment by Malakia1** [comment]
![2019-11-28_21h57_11](https://user-images.githubusercontent.com/58878574/70985872-27fcad00-20bd-11ea-8ebe-e38c08ca793b.png)
![2019-11-28_21h55_47](https://user-images.githubusercontent.com/58878574/70985882-2b903400-20bd-11ea-814e-23cbfd67f41f.png)

**Comment by KatekovAnton** [comment]
Fixed in v12 b6
