### ISSUE TITLE
[Suggestion] movement speed of units

### ISSUE THREAD

**Issue by 1GodRage** [KatekovAnton/MAXTouch-docs#40]
original MAX movement speed: https://youtu.be/iiJ1ffy8BH0?t=653
Whatever their speed, they travel into the same time. _(seems to be almost 1 second)_
It would made some replays much more enjoyable, and also some "real scout attack" more possible... Because moving 40 scouts actually takes ages... That's why we don't see it as much as we should see it.

**Comment by KatekovAnton** [comment]
I like how it is done now. All graphics-related features will be implemented only for new graphics version due to shortage of time on my side.
