### ISSUE TITLE
[Suggestion] Reorganise players order in the game creation room

### ISSUE THREAD

**Issue by 1GodRage** [KatekovAnton/MAXTouch-docs#41]
A tool to change the order of players would be useful.

![unknown](https://user-images.githubusercontent.com/63362446/81348438-56a41000-90be-11ea-8236-35853672b659.png)

_(by Chadov on 12/07/2019)_

**Comment by KatekovAnton** [comment]
Closing due to duplicate https://github.com/KatekovAnton/MAXTouch-docs/issues/31
