### ISSUE TITLE
[Suggestion] Fog of war: ghostly buildings

### ISSUE THREAD

**Issue by 1GodRage** [KatekovAnton/MAXTouch-docs#46]
switchable overlay that shows previously detected buildings of the enemy that are now in the fog

_(**Malakia** on 21/11/2018)_

**Comment by Hruks** [comment]
<img width="1136" alt="Screenshot 2021-03-04 at 15 20 47" src="https://user-images.githubusercontent.com/556824/109963265-4324fe00-7cfd-11eb-960e-278b4fda4ce3.png">

**Comment by Hruks** [comment]
<img width="1136" alt="Screenshot 2021-03-04 at 15 33 06" src="https://user-images.githubusercontent.com/556824/109964657-01955280-7cff-11eb-8e61-4c54f3b64cba.png">

**Comment by Malakia1** [comment]
Limit ghostly view only to buildings might be better?
Or buildings, engineers and constructors only
Seems a bit confusing to see all units as well

**Comment by Hruks** [comment]
> Limit ghostly view only to buildings might be better?
> Or buildings, engineers and constructors only
> Seems a bit confusing to see all units as well

Why are you confused with units in fog of war? The map cells updated when uncovered by scan and units removed if uncovered in new positions.  
It is extremely helpful information. One thing to improve is highlight already scanned cells and not scanned cells. But I did not have good interface solution for.

**Comment by Malakia1** [comment]
Yeah, it's fine. I'm OK with it, just thought some might find  it confusing, eg when a lot of units are close to edge of fog area
