### ISSUE TITLE
[Voting] Extracting resources from surrendered players units

### ISSUE THREAD

**Issue by KatekovAnton** [KatekovAnton/MAXTouch-docs#48]
lets vote if we want it or not! Press "reactions" (top-right of this message bubble) and choose +1 or -1

Discord link: https://discord.com/channels/411014559613059092/434182652610871297/774950822211092552

**Comment by 1GodRage** [comment]
I would like to allow that possibility with maybe infiltrators, as on their picture, they are hackers. And so, to allow the unit/building to transfer to our units, isn't hacking needed? It's kind of partial control... It would be a new action for infiltrators, and maybe it would also give this unity a new real utility. :p

**Comment by iindex** [comment]
Imho bad idea, it is different player and you should not have access ti his resources.  Units should be captured, perhaps it is good to allow to capture buildings of capitulated player, but it should take some effort to capture big buildings.

**Comment by KatekovAnton** [comment]
decided not to do
