### ISSUE TITLE
Remove gold from under the first mining station

### ISSUE THREAD

**Issue by KatekovAnton** [KatekovAnton/MAXTouch-docs#49]
To prevent situations like 
![2020-11-18_23h52_56](https://user-images.githubusercontent.com/992894/99644169-f04a7200-2a90-11eb-94f4-437f5967e2da.png)

**Comment by 1GodRage** [comment]
It's a special bonus landing! :D

**Comment by KatekovAnton** [comment]
we cannot remove it because resource map generates one time and cannot be rewritten anymore.
