### ISSUE TITLE
[Suggestion] Add at least "0" to starting credits values

### ISSUE THREAD

**Issue by ConstantTrue** [KatekovAnton/MAXTouch-docs#52]
More values, if possible:
a) 0 and 25;
b) 0, 10, 20, 30, 40;
c) 0, 5, 10, 15, 20, 25, 30, 35, 40, 45;
d) 0, 2, 4, 6, 8, 10, 12, 14, 16, ..., 46, 48;
e) 1, 2, 3, 4, 5, 6, 7, 8, ..., 48, 49.
("e" is much better)

**Comment by KatekovAnton** [comment]
done in v15.0.0b8
