### ISSUE TITLE
[Suggestion] Campaign cutscene capabilities

### ISSUE THREAD

**Issue by KatekovAnton** [KatekovAnton/MAXTouch-docs#59]
Scenarios:
1. When editing, it would be interesting to have also the option for damage buildings
(show the status bar), and the debris for destroyed ones, eventually.
2. The Textwindow overlap the map... I will try to suggest a low part layout in this case.
3. The clan name is not visible in “End Turn” tab, because the name color seems the same
with the background.
4. Spelling mistake: In the text in “Local Game” it must be “All Scenarios”.
Triggers for mission 1:
5. If player’s fuel truck destroyed, then – TextWindow - “Mission failed!”
6. If player’s power station start, then – show TextWindow – “Mission completed!”
Optional:
7. If enemy’s radar clicked, then show Speech “We have to cut the radar off and hide
our moves”

For the first mission I consider to be simple, not too many triggers and messages. Actually it is
easy to understand the objectives. The mission has almost 20 turns. I think it is a decent time
not to bore the player and even to have the replay option, been short, with few units to move.

The next one will be more complex. But again, IMO the missions have to stay clear, to be
relative fast, with not many units or factories to manage, because otherwise the player could be
lost or overwhelmed. It has to be straight forward!

Thank you
[TestMission.zip](https://github.com/KatekovAnton/MAXTouch-docs/files/5652945/TestMission.zip)

**Comment by KatekovAnton** [comment]
> 1. 

new action`setUnitParameter` with keys `_unitName` and `_parameter` with values ("SPEED", "HEALTH", "SHOTS", "GAS", "AMMO", "FUEL", "GOLD", "MATERIAL")
new action `killUnit` with key `_unitName`

> 2. 

waiting for your design then! reopen issue when ready

> 3. 

Player name you mean? We have a different task for it https://github.com/KatekovAnton/MAXTouch-docs/issues/56

> 4. 

done!

> 5.
> 6.

will do later. Lets create a separate ticket for mission completion conditions https://github.com/KatekovAnton/MAXTouch-docs/issues/60

> 7.

can you try to restart trigger or just show arrow with hint there?

**Comment by marcu805** [comment]
Ok, to start with the last request at point 7.:
It would even better I think, if at mouseover then show message, not necessary also to show the arrow.
Actually I did find out how to trigger the arrow for the second, third, etc, time, and that was ok. I tested for the second mission and worked well. So for the click, let's say is fine.

Point 1.:
So these two are new... and I will go to test them in the script. Thanks!

Another suggestion: 
For missions/scenarios it would be also interesting to have a separate tab which will show the Objective. This, in order to facilitate and to get over again, when the player needs to summarize the mission objectives.

**Comment by KatekovAnton** [comment]
> It would even better I think, if at mouseover then show message, not necessary also to show the arrow.
Unfortunately we should also support touch devices that doesn't have arrow pointers

> So these two are new... and I will go to test them in the script. Thanks!
will be available from beta 27!

> For missions/scenarios it would be also interesting to have a separate tab which will show the Objective. This, in order to facilitate and to get over again, when the player needs to summarize again the mission objectives.
please create a separate ticket with design +1
