### ISSUE TITLE
You can see the build number of an enemy unit when clicking on info 

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MAXTouch-docs#6]
You can see the build number of an enemy unit when clicking on info
V12 (new UI)

**Comment by Malakia1** [comment]
![Screenshot_2019-12-17-12-57-22-202_org oldgamesalive games maxandroid](https://user-images.githubusercontent.com/58878574/70993861-33f06b00-20cd-11ea-858c-b3eb5d1c0d2a.jpg)

**Comment by KatekovAnton** [comment]
@Malakia1  please specify your version. I think you use old one.
<img width="698" alt="Screen Shot 2019-12-21 at 19 21 01" src="https://user-images.githubusercontent.com/992894/71306690-0be36d80-2427-11ea-9eeb-d42e012f47ac.png">

**Comment by Malakia1** [comment]
12.0.0 beta 3
