### ISSUE TITLE
[Suggestion] Explicit option to fire at the ground

### ISSUE THREAD

**Issue by rogual** [KatekovAnton/MAXTouch-docs#63]
Firing at the ground is useful if you suspect infiltrators are about. But you're only allowed to fire at the ground if nothing else is in that square. So, enemy infiltrators can just stand under your connectors and you can't shoot them, even if you guess correctly where they are.

Suggestion: Add "ground" or similar option to the attack menu.

**Comment by Hruks** [comment]
<img width="367" alt="Screenshot 2021-02-05 at 22 04 17" src="https://user-images.githubusercontent.com/556824/107077683-47452500-67fe-11eb-912d-76df50106a1b.png">
