### ISSUE TITLE
[Bug] Constructor is not shown on the water attack menu

### ISSUE THREAD

**Issue by KatekovAnton** [KatekovAnton/MAXTouch-docs#68]
constructor gets damaged but it was not in the attack menu
https://i.gyazo.com/de510706885413337887c84b07f152a8.mp4

**Comment by KatekovAnton** [comment]
would be great to add unit tests for different combinations!

**Comment by Hruks** [comment]
Fixed:
https://gitlab.com/void0main/maxtouch-external/-/merge_requests/32
