### ISSUE TITLE
Unit or Building info panel is partially visible  when unit is on the edge of the map

### ISSUE THREAD

**Issue by Malakia1** [KatekovAnton/MAXTouch-docs#7]
Unit or Building info panel is partially visible  when unit is on the edge of the map.
New UI.
![outofscreen](https://user-images.githubusercontent.com/58878574/71162674-eb12f080-224b-11ea-8716-d2e67584e250.png)
Screenshot from Godrage

**Comment by KatekovAnton** [comment]
done in v15.0.0b8
