### ISSUE TITLE
[Issue] Second human player in local game gets 0 credit shown

### ISSUE THREAD

**Issue by danielsahne** [KatekovAnton/MAXTouch-docs#78]
I found a bug in version 15.1.3 that also has been confirmed by Slobjok in version 16.0.0. In the complex planning phase of a local game the second human player is shown 0 available credits, although 30 were setup (see screenshot). The display is corrected as soon as the first unit or building is placed. So it is not game-breaking, but misleading.

![Screenshot](https://user-images.githubusercontent.com/84267424/118392417-f2554e00-b639-11eb-9d2e-c57e7d563505.jpg)

**Comment by KatekovAnton** [comment]
fixed in v16.1.1 beta 2
