### ISSUE TITLE
Turns remain: 0. Raw -0

### ISSUE THREAD

**Issue by zachwvk** [KatekovAnton/MAXTouch-docs#81]
Steps to reproduce this issue:
1. In a 2 human player local game, disable an opponent's active factory by destroying a connector. 
2. Save and Exit the game.
3. Reload the game and end the turn.
4. As the second player select the factory, the message "Turns remain: 0. Raw -0" is displayed.

If the second player saves then reloads the correct message will be displayed.

This was tested in both versions 16, and 15.1.3 and in both cases the issue is persistent.

![Screenshot_20210518-082956_MAXAndroid](https://user-images.githubusercontent.com/22981720/118696507-5c0d5d80-b7dc-11eb-833a-04a01029f305.jpg)

This issue will occur often in a multiplayer game, because simply ending a turn in multiplayer replaces the save, exit, reload, end turn.

**Comment by KatekovAnton** [comment]
will be fixed in v16.0.1 beta 1. but displaying may still looks as on the image above. it will recover once factory is connected back.
