### ISSUE TITLE
[Bug] Non-existent unit stay in cell

### ISSUE THREAD

**Issue by KatekovAnton** [KatekovAnton/MAXTouch-docs#82]
https://discord.com/channels/411014559613059092/413601474023784461/851881928802172939

idea: maybe there is a depot and unit scale goes to 0, unit disappear, unit ghost (units in recon) with scale 0 stay visible.

**Comment by Malakia1** [comment]
![002](https://user-images.githubusercontent.com/58878574/123784788-16ae7680-d8d8-11eb-9c79-0431abdcaae5.png)
Nexus suggested on Discord that this happens (only) when a unit is killed

**Comment by Malakia1** [comment]
Nexus :"I mean unit that were killed 7 turn ago still present if I click on its cell."

**Comment by Hruks** [comment]
This is cosmetic bug related with incorrect processing after load Saved Data.
Fixed. Under review.

**Comment by KatekovAnton** [comment]
fixed in v16.0.1
