### ISSUE TITLE
[Bug] Wrong factory production result when costs exceed mined ress

### ISSUE THREAD

**Issue by Slobjok** [KatekovAnton/MAXTouch-docs#85]
Factory on -36 does not build correctly, when too few res:  
1. Local game complex plan. Create an additional heavy factory and a power generator. 
2. Make sure you have a full mining station storage (total 25 stored). 
3. Build a constructor on max speed (-36). 
4. End turn. 

Expected result: 3 Res left in storage (assuming the start mining station has 14 income), Constructor is half built (and would need one additional turn on -36 or 2 turns on -12). 

Actual result: 3 Res left in storage. OK. BUT: Constructor is only a quarter built, as if the factory was set to -12 and not -36 before. It still needs 3 turns on -12 to finish. So -24 res just vanished. 

Found in 16.0.0. Was working in 15.0.1.

**Comment by Hruks** [comment]
Fixed (https://gitlab.com/void0main/maxtouch-external/-/merge_requests/25)
